name: Build and Deploy TeamSphere

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/teamsphere-backend
  FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/teamsphere-frontend

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug secrets
      run: |
        echo "Docker username exists: ${{ secrets.DOCKER_USERNAME != '' }}"
        echo "Docker password exists: ${{ secrets.DOCKER_PASSWORD != '' }}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        context: ./teamsphere-backend
        file: ./teamsphere-backend/Dockerfile
        push: true
        tags: |
          ${{ env.BACKEND_IMAGE }}:latest
          ${{ env.BACKEND_IMAGE }}:${{ github.sha }}

  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug secrets
      run: |
        echo "Docker username exists: ${{ secrets.DOCKER_USERNAME != '' }}"
        echo "Docker password exists: ${{ secrets.DOCKER_PASSWORD != '' }}"

    - name: Debug repository structure
      run: |
        echo "Current working directory:"
        pwd
        echo "Repository root contents:"
        ls -la
        echo "Looking for package.json files:"
        find . -name "package.json" -type f

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        if [ -d "teamsphere-frontend" ]; then
          cd teamsphere-frontend
          echo "Found teamsphere-frontend directory"
          ls -la
          npm install --legacy-peer-deps
        else
          echo "teamsphere-frontend directory not found, checking current directory for package.json"
          ls -la
          if [ -f "package.json" ]; then
            npm install --legacy-peer_deps
          else
            echo "No package.json found in current directory either"
            exit 1
          fi
        fi

    - name: Build application
      run: |
        if [ -d "teamsphere-frontend" ]; then
          cd teamsphere-frontend
          npm run build
        else
          npm run build
        fi

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend
      uses: docker/build-push-action@v5
      with:
        context: ./teamsphere-frontend
        file: ./teamsphere-frontend/Dockerfile
        push: true
        tags: |
          ${{ env.FRONTEND_IMAGE }}:latest
          ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}

  deploy-local:
    needs: [build-backend, build-frontend]
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create deployment directory
      run: |
        mkdir -p ~/teamsphere-deployment
        cp docker-compose.yml ~/teamsphere-deployment/
        cp .env ~/teamsphere-deployment/ 2>/dev/null || true

    - name: Update docker-compose for production images
      working-directory: ~/teamsphere-deployment
      run: |
        sed -i 's|build:|# build:|g' docker-compose.yml
        sed -i 's|context: ./teamsphere-backend|# context: ./teamsphere-backend|g' docker-compose.yml
        sed -i 's|context: ./teamsphere-frontend|# context: ./teamsphere-frontend|g' docker-compose.yml
        sed -i '/dockerfile: Dockerfile/c\    image: ${{ env.BACKEND_IMAGE }}:latest' docker-compose.yml

    - name: Pull latest images
      run: |
        docker pull ${{ env.BACKEND_IMAGE }}:latest
        docker pull ${{ env.FRONTEND_IMAGE }}:latest

    - name: Deploy application
      working-directory: ~/teamsphere-deployment
      run: |
        docker-compose down || true
        docker-compose up -d

    - name: Wait for services
      run: sleep 30

    - name: Health check
      run: |
        curl -f http://localhost:5001/api/projects/health || exit 1
        curl -f http://localhost || exit 1
        echo "✅ Deployment successful!"
