name: Manual Deploy to Local

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'local'
        type: choice
        options:
        - local
        - staging
      version:
        description: 'Version to deploy'
        required: true
        default: 'latest'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/teamsphere-backend
  FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/teamsphere-frontend

jobs:
  manual-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Pull specified version
      run: |
        docker pull ${{ env.BACKEND_IMAGE }}:${{ github.event.inputs.version }}
        docker pull ${{ env.FRONTEND_IMAGE }}:${{ github.event.inputs.version }}

    - name: Deploy application
      run: |
        docker-compose down || true
        BACKEND_TAG=${{ github.event.inputs.version }} FRONTEND_TAG=${{ github.event.inputs.version }} docker-compose up -d

    - name: Health check
      run: |
        sleep 30
        curl -f http://localhost:5001/api/projects/health
        echo "✅ Manual deployment successful!"
        echo "🌐 Frontend: http://localhost"
        echo "🔗 Backend: http://localhost:5001"
